"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { ArrowRight, BriefcaseBusiness, CheckCircle2, CircleHelp, Copy, Gift, Landmark, LockKeyhole, Plus, Search, ShieldCheck, Sparkles, TicketCheck, Users } from "lucide-react";
import { useMemberResource } from "@/hooks/use-member-resource";
import type { AcademySummary, DashboardSummary, Membership, Position, Referral, RewardRecord, ServiceStatus, Ticket, VipSummary, WalletState } from "@/lib/contracts";
import { mockMemberData } from "@/lib/mock-data";
import { ResourceBoundary } from "./resource-boundary";
import { DataTable, EmptyState, Input, MembershipCard, MetricCard, Modal, PageHeader, Panel, PrimaryButton, ProgressBar, SecondaryButton, Select, StatusBadge, Tabs, Textarea, WalletCard } from "./ui";
import { useAppContext } from "./providers";

const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const tone = (status: string) => status === "ACTIVE" || status === "OPERATIONAL" || status === "PAID" || status === "APPROVED" || status === "CONVERTED" ? "success" : status === "PENDING" || status === "UNDER_REVIEW" || status === "ELIGIBLE" || status === "RESPONDED" || status === "DEGRADED" ? "pending" : "neutral";

export function DashboardScreen() {
  const { session } = useAppContext();
  const resource = useMemberResource("dashboard", { ...mockMemberData.dashboard, activity: [] });
  return <><PageHeader title={`Welcome back, ${session.identity.displayName.split(" ")[0]}.`} description="Your member command center for learning, participation, referrals, rewards, and support." action={<Link className="button button-primary" href="/academy">Continue Academy <ArrowRight size={16} /></Link>} /><ResourceBoundary resource={resource}>{(data: DashboardSummary) => <>
    <div className="metric-grid"><MetricCard label="Vault XP" value={data.xp.toLocaleString()} detail="Verified learning activity" /><MetricCard label="Academy progress" value={`${data.academyPercent}%`} detail="Current learning path" /><MetricCard label="Position value" value={money(data.positionValue)} detail="Across active positions" /><MetricCard label="Open support" value={String(data.openTickets)} detail="Member operations ticket" /></div>
    <div className="content-grid dashboard-grid"><Panel title="Current learning path" description="Crypto Foundations"><div className="feature-row"><div><span className="section-label">Next lesson</span><h3>Protecting keys and recovery phrases</h3><p>Continue building the habits required to operate safely onchain.</p></div><div className="progress-orb"><strong>{data.academyPercent}%</strong><span>complete</span></div></div><ProgressBar value={data.academyPercent} /><Link className="text-link" href="/academy">Open Academy <ArrowRight size={15} /></Link></Panel><Panel title="Recent activity" description="Your latest member events">{data.activity.length ? <ul className="activity-list">{data.activity.map((item) => <li key={item.id}><span className="activity-icon"><CheckCircle2 /></span><div><strong>{item.label}</strong><p>{item.detail}</p></div><time>{item.at}</time></li>)}</ul> : <EmptyState title="No recent activity" message="Your learning and account events will appear here." />}</Panel></div>
    <Panel title="Quick access" description="Return to the tools you use most"><div className="quick-grid">{[["/vault","Vault overview",Landmark],["/positions","Review positions",BriefcaseBusiness],["/referrals","Invite a member",Users],["/rewards","Reward status",Gift],["/support","Contact support",CircleHelp]].map(([href,label,Icon]) => <Link href={href as string} key={href as string}><span><Icon size={19} /></span><strong>{label as string}</strong><ArrowRight size={16} /></Link>)}</div></Panel>
  </>}</ResourceBoundary></>;
}

export function AcademyScreen() {
  const resource = useMemberResource("academy", { ...mockMemberData.academy, modules: [] });
  return <><PageHeader title="Academy" description="Structured learning, verified progress, and a clear next step inside your member workspace." action={<PrimaryButton>Continue learning <ArrowRight size={16} /></PrimaryButton>} /><ResourceBoundary resource={resource} emptyTitle="No learning path assigned" emptyMessage="Your assigned learning path will appear here once available.">{(data: AcademySummary) => <><div className="metric-grid"><MetricCard label="Path progress" value={`${data.progressPercent}%`} detail={data.pathTitle} /><MetricCard label="Lessons complete" value={`${data.completedLessons}/${data.totalLessons}`} detail="Verified completions" /><MetricCard label="XP earned" value="2,380" detail="Learning activity" /><MetricCard label="Next action" value="Continue" detail={data.nextLesson} /></div><Panel title={data.pathTitle} description="Your current learning path"><ProgressBar value={data.progressPercent} label="Overall progress" /><div className="module-list">{data.modules.map((module, index) => <article key={module.id} data-state={module.state}><span>{String(index).padStart(2,"0")}</span><div><strong>{module.title}</strong><ProgressBar value={module.progress} /></div><StatusBadge tone={module.state === "COMPLETE" ? "success" : module.state === "ACTIVE" ? "pending" : "neutral"}>{module.state}</StatusBadge></article>)}</div></Panel></>}</ResourceBoundary></>;
}

export function RewardsScreen() {
  const resource = useMemberResource("rewards", []);
  return <><PageHeader title="Rewards" description="Track eligibility and manual review status. Rewards are never transferred from this interface." /><div className="notice"><ShieldCheck /><div><strong>Manual operations only</strong><p>This page is read-only. Approval and fulfillment require an authorized human review outside the member interface.</p></div></div><ResourceBoundary resource={resource} emptyTitle="No reward activity" emptyMessage="Eligible milestones and review history will appear here.">{(data: RewardRecord[]) => <><div className="metric-grid"><MetricCard label="Under review" value={String(data.filter((item) => item.status === "UNDER_REVIEW").length)} detail="Manual review queue" /><MetricCard label="Approved" value={String(data.filter((item) => item.status === "APPROVED").length)} detail="Awaiting operations" /><MetricCard label="Paid history" value={String(data.filter((item) => item.status === "PAID").length)} detail="Recorded fulfillment" /><MetricCard label="Locked" value={String(data.filter((item) => item.status === "LOCKED").length)} detail="Future milestones" /></div><Panel title="Reward history" description="Eligibility, review, and fulfillment records"><DataTable columns={["Reward","Amount","Status","Date","Notes"]} rows={data.map((item) => [<strong key="l">{item.label}</strong>,item.amount,<StatusBadge key="s" tone={tone(item.status)}>{item.status.replaceAll("_"," ")}</StatusBadge>,item.date ?? "Not available",item.note])} /></Panel></>}</ResourceBoundary></>;
}

export function VaultScreen() {
  const positions = useMemberResource("positions", []);
  const wallet = useMemberResource("wallet", { ...mockMemberData.wallet, address: null, verified: false, rewardReady: false, displayBalance: "Unavailable" });
  const membership = useMemberResource("membership", { ...mockMemberData.membership, status: "INACTIVE" });
  return <><PageHeader title="Vault" description="A consolidated view of membership readiness, wallet state, and participation." /><div className="identity-grid"><ResourceBoundary resource={wallet}>{(data: WalletState) => <WalletCard address={data.address} ready={data.rewardReady} balance={data.displayBalance} />}</ResourceBoundary><ResourceBoundary resource={membership}>{(data: Membership) => <MembershipCard tier={data.tier} status={data.status} since={data.since} />}</ResourceBoundary></div><ResourceBoundary resource={positions} emptyTitle="No vault participation" emptyMessage="Active participation records will appear here.">{(data: Position[]) => <Panel title="Participation matrix" description="Current position and program status"><DataTable columns={["Program","Type","Participation","Status","Current value"]} rows={data.map((item) => [<strong key="n">{item.name}</strong>,item.category,item.participation,<StatusBadge key="s" tone={tone(item.status)}>{item.status}</StatusBadge>,money(item.currentValue)])} /></Panel>}</ResourceBoundary></>;
}

export function PositionsScreen() {
  const resource = useMemberResource("positions", []);
  const [tab, setTab] = useState("All positions");
  return <><PageHeader title="Positions" description="Review ownership, royalty, and portfolio participation in one place." /><Tabs items={["All positions","Active","Pending"]} active={tab} onChange={setTab} /><ResourceBoundary resource={resource} emptyTitle="No positions found" emptyMessage="Position records will appear after they are connected to your member profile.">{(data: Position[]) => { const rows = data.filter((item) => tab === "All positions" || item.status === tab.toUpperCase()); return <><div className="metric-grid"><MetricCard label="Principal" value={money(data.reduce((sum,item) => sum + item.principal,0))} detail="Recorded principal" /><MetricCard label="Current value" value={money(data.reduce((sum,item) => sum + item.currentValue,0))} detail="Across all positions" /><MetricCard label="Active" value={String(data.filter((item) => item.status === "ACTIVE").length)} detail="Current participation" /><MetricCard label="Pending" value={String(data.filter((item) => item.status === "PENDING").length)} detail="Under review" /></div><Panel title="Position register"><DataTable columns={["Position","Category","Principal","Current value","Status"]} rows={rows.map((item) => [<strong key="n">{item.name}</strong>,item.category,money(item.principal),money(item.currentValue),<StatusBadge key="s" tone={tone(item.status)}>{item.status}</StatusBadge>])} /></Panel></>; }}</ResourceBoundary></>;
}

export function ReferralsScreen() {
  const resource = useMemberResource("referrals", []);
  const [message,setMessage] = useState("");
  const [submitting,setSubmitting] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitting(true); const form = new FormData(event.currentTarget); const result = await resource.submit("/v1/member/referrals", { name: String(form.get("name")), phone: String(form.get("phone")), relationship: String(form.get("relationship")) }); setMessage(result.message); setSubmitting(false); event.currentTarget.reset(); }
  return <><PageHeader title="Referrals" description="Share your member link, submit warm introductions, and track follow-up status." /><div className="content-grid form-grid"><Panel title="Your referral link" description="Share this link with people you know"><div className="copy-field"><code>member.ironvaulttoken.com/r/ALEX7V</code><SecondaryButton onClick={() => void navigator.clipboard.writeText("member.ironvaulttoken.com/r/ALEX7V")}><Copy size={15} /> Copy</SecondaryButton></div><div className="mini-metrics"><div><strong>7</strong><span>Total referrals</span></div><div><strong>1</strong><span>Converted</span></div></div></Panel><Panel title="Submit a referral" description="Member operations will handle outreach"><form className="form-stack" onSubmit={submit}><label>Name<Input name="name" required placeholder="Full name" /></label><label>Phone<Input name="phone" required placeholder="(555) 000-0000" /></label><label>Relationship<Select name="relationship" defaultValue="Friend"><option>Friend</option><option>Family</option><option>Business</option><option>Colleague</option></Select></label><PrimaryButton disabled={submitting}>{submitting ? "Saving locally..." : <><Plus size={16} /> Add referral</>}</PrimaryButton>{message && <p className="mock-confirmation">{message}</p>}</form></Panel></div><ResourceBoundary resource={resource} emptyTitle="No referrals submitted" emptyMessage="Use the referral form to add your first introduction.">{(data: Referral[]) => <Panel title="Referral activity"><DataTable columns={["Name","Relationship","Submitted","Status"]} rows={data.map((item) => [<strong key="n">{item.name}</strong>,item.relationship,item.createdAt,<StatusBadge key="s" tone={tone(item.status)}>{item.status}</StatusBadge>])} /></Panel>}</ResourceBoundary></>;
}

export function VipScreen() {
  const resource = useMemberResource("vip", { eligible: false, status: "LOCKED", benefits: [] });
  return <><PageHeader title="VIP" description="Your premium member access, benefits, and partner briefings." /><ResourceBoundary resource={resource} emptyTitle="VIP access is not active" emptyMessage="Eligibility and premium benefits will appear after manual review.">{(data: VipSummary) => <><Panel className="vip-feature"><div className="vip-icon"><Sparkles /></div><span className="section-label">VIP membership</span><h2>Operate with priority access.</h2><p>Private briefings, priority support, and early access are coordinated through your member profile.</p><StatusBadge tone={data.status === "ACTIVE" ? "success" : "pending"}>{data.status}</StatusBadge></Panel><div className="benefit-grid">{data.benefits.map((item) => <Panel key={item.title} title={item.title}><p>{item.detail}</p></Panel>)}</div></>}</ResourceBoundary></>;
}

export function StatusScreen() {
  const resource = useMemberResource("status", { overall: "OPERATIONAL", services: [], notices: [] });
  return <><PageHeader title="Status" description="Current availability and operational notices for your member services." /><ResourceBoundary resource={resource} emptyTitle="No status data" emptyMessage="Service checks are temporarily unavailable.">{(data: ServiceStatus) => <><Panel className="status-overview"><div><span className="status-pulse" /><div><span className="section-label">Current status</span><h2>All core member services operational</h2></div></div><StatusBadge tone={tone(data.overall)}>{data.overall}</StatusBadge></Panel><Panel title="Service health"><ul className="service-list">{data.services.map((service) => <li key={service.name}><div><strong>{service.name}</strong><p>{service.detail}</p></div><StatusBadge tone={tone(service.status)}>{service.status}</StatusBadge></li>)}</ul></Panel><Panel title="Operational notices">{data.notices.map((notice) => <div className="notice-row" key={notice.title}><div><strong>{notice.title}</strong><p>{notice.detail}</p></div><time>{notice.date}</time></div>)}</Panel></>}</ResourceBoundary></>;
}

export function SupportScreen() {
  const resource = useMemberResource("tickets", []);
  const [message,setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const result = await resource.submit("/v1/member/tickets", { subject: String(form.get("subject")), category: String(form.get("category")), message: String(form.get("message")) }); setMessage(result.message); event.currentTarget.reset(); }
  return <><PageHeader title="Support" description="Open a request and review your conversations with member operations." /><div className="content-grid form-grid"><Panel title="Open a support ticket" description="Tell us what you need help with"><form className="form-stack" onSubmit={submit}><label>Subject<Input required name="subject" placeholder="How can we help?" /></label><label>Category<Select name="category"><option>Account</option><option>Wallet</option><option>Academy</option><option>Membership</option><option>Other</option></Select></label><label>Message<Textarea required name="message" rows={5} placeholder="Add the details member operations needs..." /></label><PrimaryButton><TicketCheck size={16} /> Submit ticket</PrimaryButton>{message && <p className="mock-confirmation">{message}</p>}</form></Panel><Panel title="Response expectations" description="Member operations"><div className="support-guide"><CircleHelp /><h3>We will keep the thread here.</h3><p>Replies and status changes appear in your ticket history. Never include seed phrases or private keys.</p></div></Panel></div><ResourceBoundary resource={resource} emptyTitle="No support tickets" emptyMessage="Your support history is clear.">{(data: Ticket[]) => <Panel title="Ticket history"><DataTable columns={["Ticket","Subject","Updated","Status"]} rows={data.map((item) => [item.id,<strong key="s">{item.subject}</strong>,item.updatedAt,<StatusBadge key="b" tone={tone(item.status)}>{item.status}</StatusBadge>])} /></Panel>}</ResourceBoundary></>;
}

export function AccountScreen() {
  const { session } = useAppContext();
  const wallet = useMemberResource("wallet", mockMemberData.wallet);
  const membership = useMemberResource("membership", mockMemberData.membership);
  return <><PageHeader title="Account" description="Identity, membership, wallet readiness, and communication preferences." /><Panel title="Member identity"><div className="account-identity"><div className="avatar avatar-large">{session.identity.initials}</div><div><h3>{session.identity.displayName}</h3><p>{session.identity.email}</p><StatusBadge tone="success">{session.identity.role}</StatusBadge></div></div></Panel><div className="identity-grid"><ResourceBoundary resource={wallet}>{(data: WalletState) => <WalletCard address={data.address} ready={data.rewardReady} balance={data.displayBalance} />}</ResourceBoundary><ResourceBoundary resource={membership}>{(data: Membership) => <MembershipCard tier={data.tier} status={data.status} since={data.since} />}</ResourceBoundary></div><Panel title="Profile details"><form className="form-grid-fields" onSubmit={(event) => event.preventDefault()}><label>Display name<Input defaultValue={session.identity.displayName} /></label><label>Email<Input defaultValue={session.identity.email} disabled /></label><label>Time zone<Select defaultValue="America/Phoenix"><option>America/Phoenix</option><option>America/New_York</option><option>America/Chicago</option><option>America/Los_Angeles</option></Select></label><label>Updates<Select defaultValue="Important only"><option>Important only</option><option>All member updates</option><option>None</option></Select></label><div className="form-actions"><SecondaryButton type="button">Cancel</SecondaryButton><PrimaryButton type="button">Save locally</PrimaryButton></div></form></Panel></>;
}

export function AdminRewardsScreen() {
  const resource = useMemberResource("rewards", []);
  const [selected,setSelected] = useState<RewardRecord | null>(null);
  const [query,setQuery] = useState("");
  return <><PageHeader title="Admin rewards" description="Review member eligibility and fulfillment history. No asset-transfer controls exist here." /><div className="notice"><LockKeyhole /><div><strong>Review-only administrator surface</strong><p>Automatic payout, signer, retry, worker, and cron behavior has been permanently excluded.</p></div></div><ResourceBoundary resource={resource} emptyTitle="No reward reviews" emptyMessage="The manual review queue is currently clear.">{(data: RewardRecord[]) => { const filtered = data.filter((item) => item.label.toLowerCase().includes(query.toLowerCase())); return <><div className="metric-grid"><MetricCard label="Review queue" value={String(data.filter((item) => item.status === "UNDER_REVIEW").length)} detail="Requires human review" /><MetricCard label="Eligible" value={String(data.filter((item) => item.status === "ELIGIBLE").length)} detail="Ready for review" /><MetricCard label="Approved records" value={String(data.filter((item) => item.status === "APPROVED").length)} detail="No transfer action" /><MetricCard label="Failed transfers" value="0" detail="Transfer system absent" /></div><Panel title="Manual review queue" action={<div className="search-field"><Search size={16} /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search rewards" /></div>}><DataTable columns={["Member reward","Amount","Status","Submitted","Review"]} rows={filtered.map((item) => [<strong key="l">{item.label}</strong>,item.amount,<StatusBadge key="s" tone={tone(item.status)}>{item.status.replaceAll("_"," ")}</StatusBadge>,item.date ?? "Not submitted",<SecondaryButton key="b" onClick={() => setSelected(item)}>Review</SecondaryButton>])} /></Panel><Modal open={Boolean(selected)} title="Reward review record" onClose={() => setSelected(null)}>{selected && <div className="review-record"><span className="section-label">{selected.id}</span><h3>{selected.label}</h3><dl><div><dt>Amount</dt><dd>{selected.amount}</dd></div><div><dt>Status</dt><dd>{selected.status}</dd></div><div><dt>Submitted</dt><dd>{selected.date ?? "Not submitted"}</dd></div></dl><p>{selected.note}</p><div className="notice compact"><ShieldCheck /><p>Record only. Fulfillment must be completed and recorded through approved manual operations.</p></div><div className="modal-actions"><SecondaryButton onClick={() => setSelected(null)}>Close</SecondaryButton></div></div>}</Modal></>; }}</ResourceBoundary></>;
}
